DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS figures;
DROP TABLE IF EXISTS posts;


CREATE TABLE stores(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
INSERT INTO stores(id) VALUES (1);



CREATE TABLE employees(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- store_id INT, FOREIGN kEY(store_id) REFERENCES stores(id),
    employee_name VARCHAR,
    position VARCHAR,
    salary FLOAT
);
\COPY employees FROM 'employee.csv' DELIMITER ',' CSV HEADER;
SELECT setval('employees_id_seq',(SELECT MAX(id) FROM employees));
-- INSERT INTO employees(id,store_id,full_name) VALUES (1,1,'Kenny Welcome');


CREATE TABLE games(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id),
    game_title VARCHAR,
    quantity INT,
    price FLOAT
);
\COPY games FROM 'game.csv' DELIMITER ',' CSV HEADER;
SELECT setval('games_id_seq',(SELECT MAX(id) FROM games));


CREATE TABLE figures(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id),
    action_figure_title VARCHAR,
    quantity INT,
    price FLOAT
);
\COPY figures FROM 'action_figure.csv' DELIMITER ',' CSV HEADER;
SELECT setval('figures_id_seq',(SELECT MAX(id) FROM figures));
-- INSERT INTO figures(id,store_id,name_figure,quantity) VALUES (1,1,'GOKU',25);



CREATE TABLE posts(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poster_title VARCHAR,
    -- store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id),
    quantity INT,
    price FLOAT
);
\COPY posts FROM 'poster.csv' DELIMITER ',' CSV HEADER;
SELECT setval('posts_id_seq',(SELECT MAX(id) FROM posts));
-- INSERT INTO posts(poster_title,quantity,price) VALUES ('GOKU',25,14.99);



