DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS figures;
DROP TABLE IF EXISTS posts;


CREATE TABLE stores(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
INSERT INTO stores(id) VALUES (1);



CREATE TABLE employees(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INT, FOREIGN kEY(store_id) REFERENCES stores(id),
    full_name VARCHAR
);
INSERT INTO employees(id,store_id,full_name) VALUES (1,1,'Kenny Welcome');



CREATE TABLE figures(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id),
    action_figure_title VARCHAR,
    quantity INT,
    price FLOAT
);
-- INSERT INTO figures(id,store_id,name_figure,quantity) VALUES (1,1,'GOKU',25);
\COPY figures FROM 'action_figure.csv' DELIMITER ',' CSV HEADER;


CREATE TABLE posts(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poster_title VARCHAR,
    -- store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id),
    quantity INT,
    price FLOAT
    -- store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id)
);
-- INSERT INTO posts(id,store_id,poster_title,quantity) VALUES (1,1,'GOKU',25);
\COPY posts FROM 'poster.csv' DELIMITER ',' CSV HEADER;
-- SELECT setval(pg_get_serial_sequence('posts', 'id'), COALESCE(MAX(id), 1), true) FROM posts;
SELECT setval('posts_id_seq',(SELECT MAX(id) FROM posts))

INSERT INTO posts(id,poster_title,quantity,price) VALUES ('GOKU',25,14.99);



