DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS figures;
DROP TABLE IF EXISTS posts;


CREATE TABLE stores(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
INSERT INTO stores(id) VALUES (1);


CREATE TABLE employees(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INT, FOREIGN kEY(store_id) REFERENCES stores(id),
    full_name VARCHAR
);
INSERT INTO employees(id,store_id,full_name) VALUES (1,1,'Kenny Welcome');


CREATE TABLE figures(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id),
    name_figure VARCHAR,
    quantity BIGINT
);
INSERT INTO figures(id,store_id,name_figure,quantity) VALUES (1,1,'GOKU',25);

CREATE TABLE posts(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INT, FOREIGN KEY(store_id) REFERENCES stores(id),
    name_post VARCHAR,
    quantity BIGINT
);
INSERT INTO posts(id,store_id,name_post,quantity) VALUES (1,1,'GOKU',25);
